#cloud-config
autoinstall:
  version: 1

  source:
    id: ubuntu-server-minimal

  locale: es_ES.UTF-8
  keyboard:
    layout: es
  timezone: Europe/Madrid

  network:
    version: 2
    ethernets:
      enp1s0:
        dhcp4: true

  identity:
    username: fran
    hostname: fran
    password: 'fran'

  packages:
    - python3-pip

  snaps:
    - name: pycharm-community
      channel: stable 
      classic: true
